# Generated by Django 4.1.3 on 2022-12-05 00:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admins', '0001_initial'),
        ('stands', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Umbrella',
            fields=[
                ('umbrella_id', models.AutoField(primary_key=True, serialize=False)),
                ('disrepair_rate', models.FloatField()),
                ('image_url', models.TextField()),
                ('status', models.TextField()),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admins.admin')),
                ('stand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stands.stand')),
            ],
            options={
                'db_table': 'umbrellas',
            },
        ),
    ]
