//components
export {default as AppLogin} from 'common/components/AppLogin'
export {default as AppMain} from 'common/components/AppMain'
export {default as AppMainRent} from 'common/components/AppMainRent'
export {default as AppNav} from 'common/components/AppNav'
export {default as AppSetPayInfo} from 'common/components/AppSetPayInfo'
export {default as AppSetPayModify} from 'common/components/AppSetPayModify'
export {default as AppSetSettings} from 'common/components/AppSetSettings'
export {default as AppSetUInfo} from 'common/components/AppSetUInfo'
export {default as AppStart} from 'common/components/AppStart'
export {default as Main} from 'common/components/Main'
export {default as MngDemand} from 'common/components/MngDemand'
export {default as MngMenu} from 'common/components/MngMenu'
export {default as MngUserInfo} from 'common/components/MngUserInfo'
export {default as Nav} from 'common/components/Nav'

//containers
export {default as AppHome} from 'common/containers/AppHome'
export {default as Home} from 'common/containers/Home'
export {default as ManagerPages} from 'common/containers/ManagerPages'