# Generated by Django 4.1.3 on 2022-12-05 00:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admins', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.TextField()),
                ('nickname', models.TextField()),
                ('password', models.TextField()),
                ('age', models.IntegerField()),
                ('address', models.TextField()),
                ('most_used_location', models.TextField()),
                ('count_month', models.IntegerField()),
                ('current_location', models.TextField()),
                ('pay_info', models.TextField()),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admins.admin')),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
