# Generated by Django 4.1.3 on 2022-12-05 00:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admins', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stand',
            fields=[
                ('stand_id', models.AutoField(primary_key=True, serialize=False)),
                ('district', models.TextField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admins.admin')),
            ],
            options={
                'db_table': 'stands',
            },
        ),
    ]
